import csv
import pymongo
import requests
from pymongo import MongoClient
from datetime import datetime

# MongoDB and API configuration
MONGO_URI = 'mongodb://mongo:27017'
DB_NAME = 'sample_training'
COLLECTION_NAME = 'posts'
API_URL = 'http://server:5050/posts'

# Function to import CSV data into MongoDB
def import_csv_to_mongo(csv_file, mongo_uri, db_name, collection_name):
    client = MongoClient(mongo_uri)
    db = client[db_name]
    collection = db[collection_name]

    with open(csv_file, 'r', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        for row in reader:
            # Remove "_id" to let MongoDB generate its own ObjectId
            if "_id" in row:
                del row["_id"]
            # Adjust date format to match the actual format in your CSV
            row["date"] = datetime.strptime(row["date"], "%Y-%m-%dT%H:%M:%S.%f")
            # Convert "tags" from string to list
            row["tags"] = row["tags"].split(',')
            collection.insert_one(row)

    print(f"Data imported to MongoDB collection '{collection_name}'")

# Function to create a new post via the API
def create_new_post(api_url, post_data):
    response = requests.post(api_url, json=post_data)
    if response.status_code == 200:
        print("New post created successfully")
    else:
        print(f"Failed to create post: {response.status_code}")

# Function to list all posts and save to CSV
def list_posts_and_save_to_csv(mongo_uri, db_name, collection_name, output_csv_file):
    client = MongoClient(mongo_uri)
    db = client[db_name]
    collection = db[collection_name]

    posts = list(collection.find())
    with open(output_csv_file, 'w', newline='', encoding='utf-8') as csvfile:
        fieldnames = ["_id", "author", "title", "tags", "body", "date"]
        writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
        writer.writeheader()
        for post in posts:
            post["_id"] = str(post["_id"])
            post["date"] = post["date"].isoformat() + 'Z'
            post["tags"] = ','.join(post["tags"])
            writer.writerow(post)

    print(f"All posts saved to '{output_csv_file}'")

if __name__ == "__main__":
    # Import the CSV file to MongoDB
    import_csv_to_mongo('sample_posts.csv', MONGO_URI, DB_NAME, COLLECTION_NAME)

    # Print total posts before new post creation
    client = MongoClient(MONGO_URI)
    db = client[DB_NAME]
    collection = db[COLLECTION_NAME]
    total_posts_before = collection.count_documents({})
    print(f"Total posts before: {total_posts_before}")

    # Create a new post via the API
    new_post = {
        "author": "Job",
        "title": "Post Generated By Reuqest",
        "tags": ["new", "post"],
        "body": "This post was generated.",
        "date": datetime.utcnow().isoformat() + 'Z'
    }
    create_new_post(API_URL, new_post)

    # Print total posts after new post creation
    total_posts_after = collection.count_documents({})
    print(f"Total posts after: {total_posts_after}")

    # List all posts and save to CSV
    list_posts_and_save_to_csv(MONGO_URI, DB_NAME, COLLECTION_NAME, 'all_posts.csv')